/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Timer.h"
#include "Timer_isr.h"
#include "Ultrasonido_aliases.h"
#include "Ultrasonido.h"
#include "Counter.h"
#include "Clock_1.h"
#include "Contador_isr.h"
#include "Boton_1_aliases.h"
#include "Boton_1.h"
#include "Clock_2.h"
#include "Boton_2_aliases.h"
#include "Boton_2.h"
#include "Clock_3.h"
#include "Boton2_isr.h"
#include "LCD.h"
#include "Trigger_aliases.h"
#include "Trigger.h"
#include "PWMClk.h"
#include "PWM.h"
#include "Boton1_isr.h"
#include "Pin_aliases.h"
#include "Pin.h"
#include "ADC.h"
#include "Temperatura_aliases.h"
#include "Temperatura.h"
#include "Opamp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

